/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wrs;

import java.awt.Color;
import wrs.customer.ManageCustomer;
import wrs.sales.SalesReport;

import java.util.Timer;
import java.util.TimerTask;

import java.sql.*;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        Timer dateInfotimer = new Timer();
        dateInfotimer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                String currentDateTime = SystemWRS.getCurrentDateTime();
                datetimeLBL.setText(currentDateTime);
                //System.out.println(currentDateTime);
                
                if(SystemWRS.newCustomerState ==  true)
                {
                    setEnabled(false);
                }
                else
                {
                    setEnabled(true);
                }
            }
        }, 0, 1000);
        updateGallon();
        
        
    }
    
    public void updateGallon()
    {
        Connection conn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        try
        {
            conn = SystemWRS.MsSqlDB();
            ps = conn.prepareStatement("SELECT * from system_numeric_data where name = ?");
            ps.setString(1, "Gallon_Slim");
            rs = ps.executeQuery();
            int slim_val = 0;
            int slim_val_total = 0;
            if (rs.next())
            {
                slim_val = rs.getInt("value");
                slim_val_total = rs.getInt("total");
            }
            
            String db_slim_value = Integer.toString(slim_val);
            if(SystemWRS.calcPercent(slim_val_total,slim_val) <= 30.0 && SystemWRS.calcPercent(slim_val_total,slim_val) >= 11.0)
            {
                slimLBL.setForeground(Color.blue);
            }
            else if(SystemWRS.calcPercent(slim_val_total,slim_val) <= 10.0)
            {
                slimLBL.setForeground(Color.red);
            }
            slimLBL.setText("Slim: " + db_slim_value);

            ps.setString(1, "Gallon_Round");
            rs = ps.executeQuery();
            int round_val = 0;
            int round_val_total = 0;
            if (rs.next())
            {
                round_val = rs.getInt("value");
                round_val_total = rs.getInt("total");
            }
            String db_round_value = Integer.toString(round_val);
            
            
            if(SystemWRS.calcPercent(round_val_total,round_val) <= 30.0 && SystemWRS.calcPercent(round_val_total,round_val) >= 11.0)
            {
                roundLBL.setForeground(Color.blue);
            }
            else if(SystemWRS.calcPercent(round_val_total,round_val) <= 10.0)
            {
                roundLBL.setForeground(Color.red);
            }
            roundLBL.setText("Round: " + db_round_value);
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPNL = new javax.swing.JPanel();
        datetimeLBL = new javax.swing.JLabel();
        registerCustBTN = new javax.swing.JButton();
        manageCustBTN = new javax.swing.JButton();
        placeOrderBTN = new javax.swing.JButton();
        wrsLBL = new javax.swing.JLabel();
        infoLBL = new javax.swing.JLabel();
        logoutBTN = new javax.swing.JButton();
        salesReportBTN = new javax.swing.JButton();
        roundLBL = new javax.swing.JLabel();
        slimLBL = new javax.swing.JLabel();
        gallonLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Water Refilling Station [Menu]");
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 800));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        mainPNL.setBackground(new java.awt.Color(153, 255, 255));

        datetimeLBL.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        datetimeLBL.setText("DATE_INFORMATION");

        registerCustBTN.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        registerCustBTN.setText("Register Customer");
        registerCustBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerCustBTNActionPerformed(evt);
            }
        });

        manageCustBTN.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        manageCustBTN.setText("Manage Customer");
        manageCustBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustBTNActionPerformed(evt);
            }
        });

        placeOrderBTN.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        placeOrderBTN.setText("Place Order");
        placeOrderBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderBTNActionPerformed(evt);
            }
        });

        wrsLBL.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        wrsLBL.setText("Water Refilling Station");

        infoLBL.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        infoLBL.setText("Inventory and Monitoring System");

        logoutBTN.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        logoutBTN.setText("Log Out");
        logoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTNActionPerformed(evt);
            }
        });

        salesReportBTN.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        salesReportBTN.setText("Sales Report");
        salesReportBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesReportBTNActionPerformed(evt);
            }
        });

        roundLBL.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        roundLBL.setText("Round: -");

        slimLBL.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        slimLBL.setText("Slim: -");

        gallonLBL.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        gallonLBL.setText("Gallon Available");

        javax.swing.GroupLayout mainPNLLayout = new javax.swing.GroupLayout(mainPNL);
        mainPNL.setLayout(mainPNLLayout);
        mainPNLLayout.setHorizontalGroup(
            mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPNLLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPNLLayout.createSequentialGroup()
                        .addComponent(registerCustBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 400, Short.MAX_VALUE)
                        .addComponent(logoutBTN))
                    .addGroup(mainPNLLayout.createSequentialGroup()
                        .addGroup(mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wrsLBL)
                            .addComponent(infoLBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(datetimeLBL))
                    .addGroup(mainPNLLayout.createSequentialGroup()
                        .addComponent(manageCustBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(mainPNLLayout.createSequentialGroup()
                                .addComponent(gallonLBL)
                                .addGap(53, 53, 53)
                                .addComponent(roundLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(slimLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(salesReportBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(placeOrderBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(40, 40, 40))
        );
        mainPNLLayout.setVerticalGroup(
            mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPNLLayout.createSequentialGroup()
                        .addComponent(wrsLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoLBL))
                    .addGroup(mainPNLLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(datetimeLBL)))
                .addGap(21, 21, 21)
                .addGroup(mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roundLBL)
                    .addComponent(slimLBL)
                    .addComponent(gallonLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageCustBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPNLLayout.createSequentialGroup()
                        .addComponent(placeOrderBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(salesReportBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(mainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerCustBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutBTN, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(mainPNL, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTNActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                dispose();
                
            }
        });
    }//GEN-LAST:event_logoutBTNActionPerformed

    private void registerCustBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerCustBTNActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SystemWRS.newCustomerState = true;
                new NewCustomer().setVisible(true);
            } 
        });
    }//GEN-LAST:event_registerCustBTNActionPerformed

    private void salesReportBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesReportBTNActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesReport().setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_salesReportBTNActionPerformed

    private void placeOrderBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderBTNActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }//GEN-LAST:event_placeOrderBTNActionPerformed

    private void manageCustBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustBTNActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCustomer().setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_manageCustBTNActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        updateGallon();
    }//GEN-LAST:event_formFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        updateGallon();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datetimeLBL;
    private javax.swing.JLabel gallonLBL;
    private javax.swing.JLabel infoLBL;
    private javax.swing.JButton logoutBTN;
    private javax.swing.JPanel mainPNL;
    private javax.swing.JButton manageCustBTN;
    private javax.swing.JButton placeOrderBTN;
    private javax.swing.JButton registerCustBTN;
    private javax.swing.JLabel roundLBL;
    private javax.swing.JButton salesReportBTN;
    private javax.swing.JLabel slimLBL;
    private javax.swing.JLabel wrsLBL;
    // End of variables declaration//GEN-END:variables
}
